### ISSUE TITLE
The SDK does not work with React Native 0.73.4

### ISSUE THREAD

**Issue by manage-some** [Surile/react-native-sunmi-printer#45]
React Native has updated their version and this SDK does not work with latest versions.

**Comment by Waleed065** [comment]
@Surile 

`const hasPrinter = await SunmiPrinter.hasPrinter()
console.log(hasPrinter) // false
`

return false

This works fine for react-native "0.71.14"

**Comment by manage-some** [comment]
@Surile any progress here?

Please help to resolve this issue. Thankyou

**Comment by alexsegura** [comment]
Me I got this error: 

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(ce
 at com.reactnativesunmiprinter.SunmiPrinterModule$1.onRunResult(SunmiPrinterModule.java:45)
 at com.sunmi.peripheral.printer.ICallback$Stub.onTransact(ICallback.java:54)
 at android.os.Binder.execTransact(Binder.java:570)
```

**Comment by Surile** [comment]
Is there a new architecture enabled
---- Replied Message ----
From Alexandre ***@***.***> Date 03/14/2024 17:39 To ***@***.***> Cc Bryce ***@***.***>***@***.***> Subject Re: [Surile/react-native-sunmi-printer] The SDK does not work with React Native 0.73.4 (Issue #45) 
Me I got this error:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(ce at com.reactnativesunmiprinter.SunmiPrinterModule$1.onRunResult(SunmiPrinterModule.java:45) at com.sunmi.peripheral.printer.ICallback$Stub.onTransact(ICallback.java:54) at android.os.Binder.execTransact(Binder.java:570)

**Comment by Waleed065** [comment]
> Is there a new architecture enabled ---- Replied Message ---- From Alexandre ***@***.***> Date 03/14/2024 17:39 To ***@***.***> Cc Bryce ***@***.***>***@***.***> Subject Re: [Surile/react-native-sunmi-printer] The SDK does not work with React Native 0.73.4 (Issue #45) Me I got this error: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(ce at com.reactnativesunmiprinter.SunmiPrinterModule$1.onRunResult(SunmiPrinterModule.java:45) at com.sunmi.peripheral.printer.ICallback$Stub.onTransact(ICallback.java:54) at android.os.Binder.execTransact(Binder.java:570) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@Surile  No
<img width="739" alt="Screenshot 2024-03-17 at 8 45 15 AM" src="https://github.com/Surile/react-native-sunmi-printer/assets/65929645/761d0432-c7e6-4850-a954-8896744c2629">

**Comment by Waleed065** [comment]
I was able to Solve It with by following the steps mentioned #[here](https://github.com/Surile/react-native-sunmi-printer/issues/22#issuecomment-1314951226) ✅

**Comment by Surile** [comment]
That may not support the new version, I need to rewrite it, it may take a long time
---- Replied Message ----
From Waleed ***@***.***> Date 03/17/2024 11:46 To ***@***.***> Cc Bryce ***@***.***>***@***.***> Subject Re: [Surile/react-native-sunmi-printer] The SDK does not work with React Native 0.73.4 (Issue #45) 
Is there a new architecture enabled ---- Replied Message ---- From Alexandre @.> Date 03/14/2024 17:39 To @.> Cc Bryce @.>@.> Subject Re: [Surile/react-native-sunmi-printer] The SDK does not work with React Native 0.73.4 (Issue #45) Me I got this error: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(ce at com.reactnativesunmiprinter.SunmiPrinterModule$1.onRunResult(SunmiPrinterModule.java:45) at com.sunmi.peripheral.printer.ICallback$Stub.onTransact(ICallback.java:54) at android.os.Binder.execTransact(Binder.java:570) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>
@Surile No
Screenshot.2024-03-17.at.8.45.15.AM.png (view on web)
